name: test-ppr-dynamic-io

on:
  push:
    branches: ['canary']
  pull_request:
    types: [opened, synchronize]

env:
  VERCEL_TEST_TEAM: vtest314-next-e2e-tests
  VERCEL_TEST_TOKEN: ${{ secrets.VERCEL_TEST_TOKEN }}
  DATADOG_API_KEY: ${{ secrets.DATA_DOG_API_KEY }}
  DD_ENV: 'ci'

jobs:
  changes:
    name: Determine changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 25

      - name: check for docs only change
        id: docs-change
        run: |
          echo "DOCS_ONLY<<EOF" >> $GITHUB_OUTPUT;
          echo "$(node scripts/run-for-change.js --not --type docs --exec echo 'false')" >> $GITHUB_OUTPUT;
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: check for release
        id: is-release
        run: |
          if [[ $(node ./scripts/check-is-release.js 2> /dev/null || :) = v* ]];
            then
              echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
            else
              echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
          fi

    outputs:
      docs-only: ${{ steps.docs-change.outputs.DOCS_ONLY != 'false' }}
      is-release: ${{ steps.is-release.outputs.IS_RELEASE == 'true' }}

  run-tests:
    if: ${{ (github.ref == 'refs/heads/canary' || github.head_ref == '10-10-run_ci_for_ppr_dio') }}
    name: Run Tests
    needs: changes
    uses: ./.github/workflows/build_reusable.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        group: [1/5, 2/5, 3/5, 4/5, 5/5, 6/6, 7/7, 8/8, 9/9, 10/10]
    with:
      afterBuild: __NEXT_EXPERIMENTAL_PPR=true __NEXT_EXPERIMENTAL_DIO=true NEXT_TEST_CONTINUE_ON_ERROR=1 NEXT_TEST_MODE=start node run-tests.js --timings -g ${{ matrix.group }} -c ${TEST_CONCURRENCY} --type production
      skipNativeBuild: 'yes'
      skipNativeInstall: 'no'
      stepName: 'test-ppr-dio-${{ matrix.group }}'
      runs_on_labels: '["ubuntu-latest"]'

  report-test-results-to-datadog:
    needs: run-tests
    if: ${{ always() }}

    runs-on: ubuntu-latest
    name: report test results to datadog
    steps:
      - name: Download test report artifacts
        id: download-test-reports
        uses: actions/download-artifact@v4
        with:
          pattern: test-reports-*
          path: test
          merge-multiple: true

      - name: Upload test report to datadog
        run: |
          if [ -d ./test/test-junit-report ]; then
            DD_ENV=ci npx @datadog/datadog-ci@2.23.1 junit upload --tags test.type:dynamicIO --service nextjs ./test/test-junit-report
          fi
